Settings:
    Token: "BOT-TOKEN"
    Prefix: "-"
    ServerID: "YOUR-SERVER-ID"
    Storage: "database.db"
    DevMode: false # This option will reset every addon configs.

Embeds:
    Branding: "Clode Bot"
    Color: "2f3136"
